title: CitrineOS
description: Documentation for the CitrineOS implementation of the Open Charge Point Protocol (OCPP).

baseurl: ""
url: "https://citrineos.github.io"
author: S44 LLC

plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag