version: '3.8'

services:
  citrineos.github.io:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    command: bundle exec jekyll serve --host 0.0.0.0
